# Generated by Django 3.2.8 on 2022-03-09 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('mod_date', models.DateField(auto_now_add=True)),
                ('qnty', models.IntegerField(blank=True, null=True)),
                ('open_str', models.IntegerField(blank=True, null=True)),
                ('str_qnty', models.IntegerField(blank=True)),
                ('restock', models.IntegerField(blank=True, default=0, null=True)),
                ('sales', models.IntegerField(blank=True, default=0, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('variance', models.IntegerField(blank=True, default=0)),
                ('available', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('reorder_level', models.IntegerField(blank=True, default=10)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('mode_of_sales', models.CharField(blank=True, choices=[('General', 'General'), ('Special', 'Special')], default='General', max_length=50, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.category')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('product', models.ManyToManyField(to='ims.Product')),
                ('rep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.staff')),
            ],
        ),
    ]
