# Generated by Django 3.2.8 on 2022-04-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='last_updated',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
