# Generated by Django 3.2.8 on 2022-04-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_auto_20220430_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductreport',
            name='last_updated',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='productreport',
            name='last_updated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
