# Generated by Django 3.2.8 on 2022-05-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_debtor_historicaldebtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicaldebtor',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
