# Generated by Django 3.2.8 on 2022-05-03 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_auto_20220503_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldebtor',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debtor',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
